import os
import base64

from utils.display import print_header, print_result, print_separator
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding

# ─────────────────────────────────────────────────────
# Symmetric LAB - Main Menu
# ─────────────────────────────────────────────────────
def symmetric_lab():
    # sub menu with all 9 features
    is_running = True
    while is_running:
        print_header("SYMMETRIC ENCRYPTION LAB")
        print("\n  Select a feature:")
        print("  1. Key Generator (128, 192, 256)")
        print("  2. AES Encrypt (CBC Mode)")
        print("  3. AES Decrypt (CBC Mode)")
        print("  4. ECB Mode Vs CBC Comparision")
        print("  5. CTR Mode Explorer")
        print("  6. File Encryption & Decryption")
        print("  7. CMAC Generation & Verification")
        print("  8. HMAC Generation & Verification")
        print("  9. Authenticated Encryption (AES-GCM with auth tag)")
        
        print("  0. Back to Main Menu")
        print_separator()

        choice = input("  Enter your choice: ")

        if choice == "1":
            key_generator()
        elif choice == "2":
            aes_cbc_encryption()
        elif choice == "3":
            aes_cbc_decryption()
        elif choice == "4":
            aes_ecb_cbc_comparison()
        elif choice == "5":
            aes_ctrmode_explorer()
        elif choice in ["6", "7", "8", "9"]:
            print("\n  This module is coming soon. Stay tuned.")
        elif choice == "0":
            is_running = False
        else:
            print("\n  Invalid choice. Try again.")

# ─────────────────────────────────────────────────────
# Feature 1 — Symmetric Key Generator
# ─────────────────────────────────────────────────────
def key_generator():
    print_header("SYMMETRIC KEY GENERATOR")
    print("  1. 128 bits")
    print("  2. 192 bits")
    print("  3. 256 bits")
    print("  0. Back to Main Menu")
    print_separator()
    keylength = input("  Select key size: ")

    key_options ={
        "1" : (16, 128),
        "2" : (24, 192),
        "3" : (32, 256)
    }

    if keylength in key_options:
        size_bytes, size_bits = key_options[keylength]
        key = os.urandom(size_bytes)
        print_result("Key Size", f"{size_bits} bits")
        print_result("Key (Hex)", key.hex())
        key_path = f"output/keys/symmetric_key_{size_bits}.key"
        with open(key_path, "wb") as f:
            f.write(key)
        print_result("Saved to", key_path)
    elif keylength == "0":
        return
    else:
        print("\n  Invalid choice. Try again.")

    print_separator() 

# ─────────────────────────────────────────────────────
# Feature 2 — AES - CBC Encryption
# ─────────────────────────────────────────────────────
# AES-CBC Encryption Flow:
# 1. Take plain text input from user
# 2. Load AES key from file (generated by Feature 1)
# 3. Generate random 16-byte IV (Initialization Vector)
#    - IV adds randomness so same text encrypts differently each time
#    - IV is saved to file for use during decryption
# 4. Pad plain text using PKCS7
#    - AES works on fixed 16-byte blocks
#    - PKCS7 adds bytes to make input a multiple of 16
# 5. Create AES-CBC cipher engine (key + IV)
# 6. Encrypt padded text → raw binary ciphertext
# 7. Base64 encode → convert binary to readable string
# ─────────────────────────────────────────────────────
def aes_cbc_encryption():
    print_header("AES CBC ENCRYPTION")
    plain_text = input("  Enter text to encrypt: ")

    print("  1. 128 bits")
    print("  2. 192 bits")
    print("  3. 256 bits")
    print("  0. Back to Main Menu")
    print_separator()

    key_choice = input("  Select key size: ")
    key_options = {
        "1": 128,
        "2": 192,
        "3": 256
    }

    # Load key from file
    if key_choice in key_options:
        key_bits = key_options[key_choice]
        try:
            with open(f"output/keys/symmetric_key_{key_bits}.key", "rb") as f:
                key = f.read()

        except FileNotFoundError:
            print(f"\n  Key not found. Please generate a {key_bits}-bit key first.")
            return
        # Generate IV 
        iv = os.urandom(16)
        iv_path = "output/keys/iv_key.key"
        with open(iv_path, "wb") as f:
            f.write(iv)

        # Create the padding object
        padder = padding.PKCS7(128).padder()
        # Actually Pad the plain text
        padded_text = padder.update(plain_text.encode()) + padder.finalize()

        # Create the cipher engine
        cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
        # Get encryptor from cipher. cipher object can do both encrypt and decrypt
        encryptor = cipher.encryptor()

        # Encrypt
        cipher_text = encryptor.update(padded_text) + encryptor.finalize()

        # Base64 encode output 
        cipher_text_b64 = base64.b64encode(cipher_text).decode()

        # Display result 
        print_result("Original Text", plain_text)
        print_result("Encrypted (B64)", cipher_text_b64)
        print_result("IV (Hex)", iv.hex())
        print_result("Key Size", f"{key_bits} bits")
        print_result("Saved to", iv_path)

    elif key_choice == "0":
        return
    else:
        print("\n  Invalid choice. Try again.")
        return
    print_separator()
    print("\n  Note: Use IV and same key size in Feature 3 to decrypt.")

# ─────────────────────────────────────────────────────
# Feature 3 — AES - CBC Decryption
# ─────────────────────────────────────────────────────
# AES-CBC Decryption Flow (reverse of encryption):
# 1. Take Base64 ciphertext input from user
# 2. Load same AES key used during encryption
# 3. Load saved IV from file
#    - Must be exact same IV used during encryption
#    - Different IV = garbage output
# 4. Base64 decode → convert readable string back to binary
# 5. Create AES-CBC cipher engine (same key + same IV)
# 6. Decrypt binary ciphertext → padded plain text
# 7. Remove PKCS7 padding → recover original plain text
# ─────────────────────────────────────────────────────
def aes_cbc_decryption():
    print_header("AES CBC DECRYPTION")
    cipher_text_b64 = input("  Enter cipher text (Base64) to decrypt: ")

    print("  1. 128 bits")
    print("  2. 192 bits")
    print("  3. 256 bits")
    print("  0. Back to Main Menu")
    print_separator()

    key_choice = input("  Select same key size used for encryption: ")
    key_options = {
        "1": 128,
        "2": 192,
        "3": 256
    }

    # Load key from file
    if key_choice in key_options:
        key_bits = key_options[key_choice]
        try:
            with open(f"output/keys/symmetric_key_{key_bits}.key", "rb") as f:
                key = f.read()

        except FileNotFoundError:
            print(f"\n  Key not found. Please generate a {key_bits}-bit key first.")
            return
        # Load IV 
        iv_path = "output/keys/iv_key.key"
        try:
            with open(iv_path, "rb") as f:
                iv = f.read()
        except FileNotFoundError:
            print("\n  IV not found. Please encrypt a message first (Feature 2).")
            return
        # Decode the String instead of bytes
        cipher_text = base64.b64decode(cipher_text_b64)

        # Create a cipher object for decryption
        cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
        decryptor = cipher.decryptor()

        # Decrypt the cipher text
        padded_plain_text = decryptor.update(cipher_text)+decryptor.finalize() 

        # remove the PKCS7 padding
        unpadder = padding.PKCS7(128).unpadder()
        plain_text = unpadder.update(padded_plain_text) + unpadder.finalize()

        # Display result 
        print_result("Input Cipher Text", cipher_text_b64)
        print_result("Decrypted Text", plain_text.decode())
        print_result("IV (Hex)", iv.hex())
        print_result("Key Size", f"{key_bits} bits")

    elif key_choice == "0":
        return
    else:
        print("\n  Invalid choice. Try again.")
        return

    print_separator()

# ─────────────────────────────────────────────────────
# Feature 4 — ECB vs CBC Comparison
# ─────────────────────────────────────────────────────
# ECB (Electronic Codebook):
#   - No IV — each block encrypted independently
#   - Same input block = same output block always
#   - Patterns visible in ciphertext — cryptographically weak
#   - Deprecated — never use for sensitive data
#
# CBC (Cipher Block Chaining):
#   - Uses IV — each block XORed with previous ciphertext block
#   - Same input produces different output every time
#   - No patterns visible — cryptographically strong
#   - Industry standard for symmetric encryption
#
# This feature demonstrates the difference visually:
# Part 1 — user text encrypted with both modes side by side
# Part 2 — repeating blocks prove ECB weakness definitively
# ─────────────────────────────────────────────────────
def aes_ecb_cbc_comparison():
    print_header("AES ECB VS CBC COMPARISON")

    # PART 1 — Side by side with user input
    print("\n  PART 1 — SIDE BY SIDE ENCRYPTION")

    plain_text = input("  Enter text to encrypt: ")
    print("  1. 128 bits")
    print("  2. 192 bits")
    print("  3. 256 bits")
    print("  0. Back to Main Menu")

    key_choice = input("  Select key size: ")
    key_options = {
        "1": 128,
        "2": 192,
        "3": 256
    }

    # Load key from file
    if key_choice in key_options:
        key_bits = key_options[key_choice]
        try:
            with open(f"output/keys/symmetric_key_{key_bits}.key", "rb") as f:
                key = f.read()

        except FileNotFoundError:
            print(f"\n  Key not found. Please generate a {key_bits}-bit key first.")
            return
        # Generate IV 
        iv = os.urandom(16)
        iv_path = "output/keys/iv_key.key"
        with open(iv_path, "wb") as f:
            f.write(iv)

        # Create the padding object
        padder = padding.PKCS7(128).padder()
        # Actually Pad the plain text
        padded_text = padder.update(plain_text.encode()) + padder.finalize()

        # Create the cipher engine for CBC
        cipher_cbc = Cipher(algorithms.AES(key), modes.CBC(iv))
        # Get encryptor from cipher. cipher object can do both encrypt and decrypt
        encryptor_cbc  = cipher_cbc.encryptor()

        # Encrypt
        cipher_text_cbc  = encryptor_cbc.update(padded_text) + encryptor_cbc.finalize()

        # Base64 encode output 
        cipher_text_cbc_b64  = base64.b64encode(cipher_text_cbc).decode()

        # Create the cipher engine for ecb
        cipher_ecb = Cipher(algorithms.AES(key), modes.ECB())
        # Get encryptor from cipher. cipher object can do both encrypt and decrypt
        encryptor_ecb  = cipher_ecb.encryptor()

        # Encrypt
        cipher_text_ecb = encryptor_ecb.update(padded_text) + encryptor_ecb.finalize()

        # Base64 encode output 
        cipher_text_ecb_b64 = base64.b64encode(cipher_text_ecb).decode()
        print_result("Plain Text", plain_text)
        print_result("CBC Encrypted", cipher_text_cbc_b64)
        print_result("ECB Encrypted", cipher_text_ecb_b64)

        print_separator()

        # PART 2 — Pattern Demonstration
        # Uses hardcoded repeating 16-byte blocks ("A" * 64)
        # ECB encrypts identical blocks → identical ciphertext (pattern visible)
        # CBC chains blocks with IV → every block different (no pattern)
        # Fresh IV generated for Part 2 to ensure independence from Part 1

        print("\n  PART 2 — PATTERN DEMONSTRATION")
        # Use exactly repeating 16-byte blocks
        plain_text = "AAAAAAAAAAAAAAAA" * 3
        print("  Input: 3 identical 16-byte blocks of 'A'")
        print_result("Plain Text", plain_text)
        print_separator()

        padder = padding.PKCS7(128).padder()
        padded_text = padder.update(plain_text.encode()) + padder.finalize()

        iv2 = os.urandom(16)
        cipher_cbc2 = Cipher(algorithms.AES(key), modes.CBC(iv2))
        cipher_ecb2 = Cipher(algorithms.AES(key), modes.ECB())

        encryptor_cbc2  = cipher_cbc2.encryptor()
        cipher_text_cbc2  = encryptor_cbc2.update(padded_text) + encryptor_cbc2.finalize()
        encryptor_ecb2  = cipher_ecb2.encryptor()
        cipher_text_ecb2 = encryptor_ecb2.update(padded_text) + encryptor_ecb2.finalize()

        # Split raw cipher bytes into 16-byte blocks
        blocks_cbc = [cipher_text_cbc2[i:i+16] for i in range(0, len(cipher_text_cbc2), 16)]
        print("\n  CBC Blocks:")
        for i, block in enumerate(blocks_cbc):
            print_result(f"CBC Block {i+1}", block.hex())

        blocks_ecb = [cipher_text_ecb2[i:i+16] for i in range(0, len(cipher_text_ecb2), 16)]
        print("\n  ECB Blocks:")
        for i, block in enumerate(blocks_ecb):
            if i == 0:
                suffix = " ← REFERENCE BLOCK"
            elif block.hex() == blocks_ecb[0].hex():
                suffix = " ← IDENTICAL"
            else:
                suffix = " ← DIFFERENT (padding block)"
            print_result(f"ECB Block {i+1}", block.hex() + suffix)

        print_separator()

        # OBSERVATION
        print("\n  OBSERVATION:")
        print("  ECB — identical blocks = identical ciphertext (WEAK)")
        print("  CBC — chaining makes every block unique (STRONG)")
        print("  Never use ECB for sensitive data in production.")

        input("\n  Press Enter to continue...")
        print_separator()
    elif key_choice == "0":
        return
    else:
        print("\n  Invalid choice. Try again.")
        return

# ─────────────────────────────────────────────────────
# Feature 5 — AES CTR Mode Explorer
# ─────────────────────────────────────────────────────
# CTR (Counter Mode) — Key Concepts:
#   - Converts AES block cipher into a stream cipher
#   - AES encrypts Nonce + Counter to generate keystream
#   - Plaintext XOR Keystream = Ciphertext
#   - No padding required — works on any length input
#   - Same operation for both encrypt and decrypt
#   - Supports parallel processing — faster than CBC
#   - Nonce must be unique per encryption with same key
#   - Nonce reuse with same key = catastrophic security failure
#
# Key difference from CBC:
#   - CBC encrypts plaintext directly with chaining
#   - CTR never encrypts plaintext — encrypts counter blocks
#   - CTR has no error propagation across blocks
# ─────────────────────────────────────────────────────
# ctr_encrypt():
# CTR Encryption Flow:
# 1. Take plain text input
# 2. Load AES key from file
# 3. Generate random 16-byte nonce
#    - Nonce saved to output/keys/ctr_nonce.key
#    - Never reuse nonce with same key
# 4. Create AES-CTR cipher (key + nonce)
# 5. Encrypt — no padding needed
#    - CTR generates keystream from nonce + counter
#    - XOR keystream with plaintext = ciphertext
# 6. Base64 encode → display readable output

# ctr_decrypt():
# CTR Decryption Flow (identical operation to encryption):
# 1. Take Base64 ciphertext input
# 2. Load same AES key used during encryption
# 3. Load saved nonce from file
#    - Must be exact same nonce used during encryption
# 4. Create AES-CTR cipher (same key + same nonce)
# 5. Decrypt — XOR keystream with ciphertext = plaintext
#    - Same operation as encryption due to XOR symmetry
# 6. Decode bytes to string and display
# ─────────────────────────────────────────────────────
def aes_ctrmode_explorer():
    print_header("AES CTR MODE EXPLORER")

    print("  1. 128 bits")
    print("  2. 192 bits")
    print("  3. 256 bits")
    print("  0. Back to Main Menu")
    print_separator()

    key_choice = input("  Select key size: ")
    key_options = {
        "1": 128,
        "2": 192,
        "3": 256
    }

    # Load key from file
    if key_choice in key_options:
        key_bits = key_options[key_choice]
        try:
            with open(f"output/keys/symmetric_key_{key_bits}.key", "rb") as f:
                key = f.read()

        except FileNotFoundError:
            print(f"\n  Key not found. Please generate a {key_bits}-bit key first.")
            return
        
        print_result("Key Loaded", f"AES-{key_bits} ({key_bits} bits)")
        
        print("\n  1. Encrypt")
        print("  2. Decrypt")
        print("  3. CTR Mode Information")
        print("  0. Back")
        print_separator()
        operation = input("  Select operation: ")
            
        if operation == "1":
            ctr_encrypt(key)
        elif operation == "2":
            ctr_decrypt(key)
        elif operation == "3":
            ctr_mode_information()
        else:
            print("\n  Invalid operation.")

    elif key_choice == "0":
        return
    else:
        print("\n  Invalid choice. Try again.")
        return
 
def ctr_encrypt(key):
    plain_text = input("  Enter text to encrypt: ")
    
    # Generate nonce
    nonce = os.urandom(16)
    nonce_path = "output/keys/ctr_nonce.key" 
    with open(nonce_path, "wb") as f:
        f.write(nonce)
    print_result("Saved to", nonce_path)
    print_separator()
            
    # Create the cipher engine
    cipher = Cipher(algorithms.AES(key), modes.CTR(nonce))
    # Get encryptor from cipher. cipher object can do both encrypt and decrypt
    encryptor = cipher.encryptor()

    # Encrypt
    cipher_text = encryptor.update(plain_text.encode()) + encryptor.finalize()
    
    # Base64 encode output 
    cipher_text_b64 = base64.b64encode(cipher_text).decode()
    # Display result 
    print_result("Original Text", plain_text)
    print_result("Nonce (Hex)", nonce.hex())
    print_result("Nonce Length", f"{len(nonce)} bytes")
    print_result("Key Length", f"{len(key)} bytes")
    print_result("Encrypted (B64)", cipher_text_b64)
    print_separator() 
    print("\n  Note: Use same key size in Decrypt to recover plaintext.")  

def ctr_decrypt(key):
    cipher_text_b64 = input("  Enter cipher text (Base64) to decrypt: ")
    try:
        cipher_text = base64.b64decode(cipher_text_b64)
    except Exception:
        print("\n  Invalid Base64 ciphertext.")
        return
    # Load nonce
    nonce_path = "output/keys/ctr_nonce.key" 
    try:
        with open(nonce_path, "rb") as f:
            nonce = f.read()
    except FileNotFoundError:
        print("\n  Nonce not found. Please encrypt a message first (Feature 5 → Encrypt).")
        return

    # Create the cipher engine
    cipher = Cipher(algorithms.AES(key), modes.CTR(nonce))
    # Get decryptor from cipher. cipher object can do both encrypt and decrypt
    decryptor = cipher.decryptor()
    
    # Decrypt the cipher text
    plain_text = decryptor.update(cipher_text) + decryptor.finalize() 
    try:
        decrypted_text = plain_text.decode()
    except UnicodeDecodeError:
        print("\n  Decryption failed or produced invalid text.")
        return
    # Display result 
    print_result("Input Cipher Text", cipher_text_b64)
    print_result("Nonce (Hex)", nonce.hex())
    print_result("Nonce Length", f"{len(nonce)} bytes")
    print_result("Key Length", f"{len(key)} bytes")
    print_result("Decrypted Text", decrypted_text)
    print_separator()

def ctr_mode_information():

    print_header("CTR MODE INFORMATION")

    print_result(
        "Overview",
        "CTR converts AES into a stream cipher"
    )

    print_result(
        "AES Input",
        "Nonce + Counter"
    )

    print_result(
        "Padding",
        "Not Required"
    )

    print_result(
        "Encryption",
        "Plaintext XOR Keystream"
    )

    print_result(
        "Decryption",
        "Ciphertext XOR Same Keystream"
    )

    print_result(
        "AES Operation",
        "AES Encrypt used for both Encrypt and Decrypt"
    )

    print_result(
        "Parallel Processing",
        "Encryption and Decryption Supported"
    )

    print_result(
        "Random Access",
        "Supported"
    )

    print_result(
        "Error Propagation",
        "Limited to Modified Block/Bits"
    )

    print_result(
        "Security Rule",
        "Never Reuse Same Key + Nonce"
    )

    print_separator()

    print("\n  CTR Flow:")
    print("""
    Nonce || Counter
            │
            ▼
       AES Encrypt
            │
            ▼
        Keystream
            │
            ▼
    Plaintext XOR Keystream
            │
            ▼
        Ciphertext
    """)

    print_separator()

    input("\n  Press Enter to continue...")